### ISSUE TITLE
模板字符串识别可能有问题

### ISSUE THREAD

**Issue by Banana-energy** [pekonchan/rollup-plugin-i18n-auto-demo#1]
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto-demo/assets/49467518/190ea94f-2016-415b-827c-b63ebc52c07d)
对应这种类型的字符串
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto-demo/assets/49467518/2299d1e0-bad2-48eb-b229-b98afe3280e0)

**Comment by pekonchan** [comment]
@Banana-energy 可以更新下npm包哈。 这个前段时间刚解决了

**Comment by pekonchan** [comment]
请更新到最新版0.1.5哈
