### ISSUE TITLE
根据打开的页面涉及到的文件把中文提取到`src/assets/`文件夹里

### ISSUE THREAD

**Issue by huxy1002** [pekonchan/rollup-plugin-i18n-auto-demo#2]
1.json文件只能提取到assets文件夹中嘛？我在vite.config.js文件中配置的是`path: path.resolve('src/locales')`不会生效

**Comment by huxy1002** [comment]
2.如何提取所有词条到json 而不是仅提取打开的页面

**Comment by huxy1002** [comment]
> 1.json文件只能提取到assets文件夹中嘛？我在vite.config.js文件中配置的是`path: path.resolve('src/locales')`不会生效

**Comment by pekonchan** [comment]
> locales

我刚试了，改成这样是ok的哦
<img width="334" alt="image" src="https://github.com/user-attachments/assets/173d916f-0506-4c75-9cf0-dea51c86d475">

**Comment by huxy1002** [comment]
关于第一条 在demo中确实是ok的  应该是我自己项目的问题~

**Comment by pekonchan** [comment]
> 2.如何提取所有词条到json 而不是仅提取打开的页面

build命令就可以全部词条收集到json中了。 本地开发的话，因为编译是按需编译的，所以本地开发情况下是为了实现自动编写边收集，想要完整收集或一次性收集，就build命令就行，会对本地开发收集到的情况进行查漏补缺

**Comment by huxy1002** [comment]
对于第一条 我看了下区别就是 我的json名叫zh-cn 改成zh就好了

**Comment by huxy1002** [comment]
> > 2.如何提取所有词条到json 而不是仅提取打开的页面
> 
> build命令就可以全部词条收集到json中了。 本地开发的话，因为编译是按需编译的，所以本地开发情况下是为了实现自动编写边收集，想要完整收集或一次性收集，就build命令就行，会对本地开发收集到的情况进行查漏补缺

感谢！！！

**Comment by pekonchan** [comment]
> 对于第一条 我看了下区别就是 我的json名叫zh-cn 改成zh就好了

ouput.filename 可以指定文件名

<img width="672" alt="image" src="https://github.com/user-attachments/assets/500b699a-acda-4158-bce1-559d43b93037">
